# Generated by Django 6.1.1 on 2026-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_approve_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_leads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_finances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('PROJECTS', 'Projects & Execution'), ('SALES_CRM', 'Sales & CRM'), ('DESIGN', 'Design & Architecture'), ('ENGINEERING', 'Site & Technical Engineering'), ('FINANCE', 'Finance & Billing'), ('PROCUREMENT', 'Procurement & Vendors')], db_index=True, default='PROJECTS', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('COMPANY_ADMIN', 'Company Admin / Principal'), ('PROJECT_MANAGER', 'Project Manager'), ('SITE_ENGINEER', 'Site Engineer'), ('SALES_LEAD', 'Sales & CRM Lead'), ('ARCHITECT', 'Project Architect / Designer'), ('CONTRACTOR', 'Contractor / Vendor')], db_index=True, default='ARCHITECT', max_length=30),
        ),
    ]
