# Generated by Django 6.1.1 on 2026-09-24 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_org_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(blank=True, default='', max_length=50)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('city', models.CharField(default='Gurugram', max_length=100)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('stage', models.CharField(choices=[('NEW', 'New Inbound'), ('CONTACTED', 'Initial Contact'), ('QUALIFIED', 'Site Evaluated & Qualified'), ('PROPOSAL_SENT', 'Proposal & Estimate Sent'), ('WON', 'Won & Converted'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=50)),
                ('source', models.CharField(choices=[('DIRECT', 'Direct / Walk-in'), ('WEBSITE', 'Basekraft Web Portal'), ('REFERRAL', 'Client Referral'), ('ARCHITECT', 'Architect Network'), ('CAMPAIGN', 'Digital Marketing')], db_index=True, default='DIRECT', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company')),
            ],
            options={
                'verbose_name': 'CRM Lead',
                'verbose_name_plural': 'CRM Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Structural Materials', max_length=100)),
                ('unit', models.CharField(default='Sq Ft', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='companies.company')),
            ],
            options={
                'verbose_name': 'Material / BOQ Item',
                'verbose_name_plural': 'Materials / BOQ Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(blank=True, default='', max_length=50)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('city', models.CharField(default='Gurugram', max_length=100)),
                ('stage', models.CharField(choices=[('PLANNING', 'Planning & Permits'), ('DESIGN', 'Architectural Design'), ('EXECUTION', 'Execution & Fitout'), ('HANDOVER', 'Quality & Handover'), ('COMPLETED', 'Completed')], db_index=True, default='EXECUTION', max_length=50)),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('DELAYED', 'Delayed'), ('CRITICAL', 'Critical Attention'), ('COMPLETED', 'Completed')], db_index=True, default='ON_TRACK', max_length=50)),
                ('progress_pct', models.PositiveIntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_handover', models.DateField(blank=True, null=True)),
                ('assigned_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('type', models.CharField(choices=[('RECEIVABLE', 'Client Receivable / Inflow'), ('PAYABLE', 'Vendor Payable / Outflow')], db_index=True, max_length=50)),
                ('category', models.CharField(default='Milestone Billing', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Due'), ('PAID', 'Settled & Reconciled'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='operations.project')),
            ],
            options={
                'verbose_name': 'Financial Transaction',
                'verbose_name_plural': 'Financial Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=22.5, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('APPROVED', 'Approved by Client'), ('REJECTED', 'Client Rejected')], db_index=True, default='DRAFT', max_length=50)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='operations.project')),
            ],
            options={
                'verbose_name': 'Quote / Estimate',
                'verbose_name_plural': 'Quotes / Estimates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Civil / Structural', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Released'), ('FULFILLED', 'Material Delivered / Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=50)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_orders', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='operations.project')),
            ],
            options={
                'verbose_name': 'Work / Purchase Order',
                'verbose_name_plural': 'Work / Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
