# Generated by Django 6.1.1 on 2026-09-24 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price_monthly_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_annual_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_seats', models.PositiveIntegerField(default=5)),
                ('storage_gb', models.PositiveIntegerField(default=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_monthly_inr'],
            },
        ),
    ]
