# Generated by Django 6.1.1 on 2026-09-24 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('city', models.CharField(default='Gurugram', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lead_architect', models.CharField(blank=True, default='', max_length=255)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Company Tenant',
                'verbose_name_plural': 'Company Tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
