# Generated by Django 6.1.1 on 2026-09-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('INTERIOR_DESIGN', 'Interior Design & Turnkey Fit-out'), ('SOLAR_EPC', 'Solar Energy & Rooftop EPC'), ('MODULAR_FURNITURE', 'Modular Furniture & Manufacturing'), ('CIVIL_CONSTRUCTION', 'Real Estate & Civil Construction')], db_index=True, default='INTERIOR_DESIGN', max_length=50),
        ),
    ]
