# Generated by Django 6.1.1 on 2026-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='org_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
